experiment:
  project: cross_view_transformers_test
  uuid: '0918_191717'
  save_dir: /home/jialvzou/cvt_io/logs/
  seed: 2022
  checkpoint_interval: 1000
  log_image_interval: 500
loader:
  batch_size: 5
  num_workers: 4
  pin_memory: true
  prefetch_factor: 4
optimizer:
  lr: 0.004
  weight_decay: 1.0e-07
scheduler:
  div_factor: 10
  pct_start: 0.3
  final_div_factor: 10
  max_lr: 0.004
  total_steps: 100001
  cycle_momentum: false
trainer:
  max_steps: 100001
  log_every_n_steps: 50
  gpus:
  - 1
  - 2
  precision: 32
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  gradient_clip_val: 5.0
  sync_batchnorm: false
model:
  _target_: cross_view_transformer.model.cvt.CrossViewTransformer
  dim_last: 64
  outputs:
    bev:
    - 0
    - 1
    center:
    - 1
    - 2
  encoder:
    _target_: cross_view_transformer.model.encoder.Encoder
    dim: 128
    scale: 1.0
    middle:
    - 2
    - 2
    backbone:
      _target_: cross_view_transformer.model.backbones.efficientnet.EfficientNetExtractor
      model_name: efficientnet-b4
      layer_names:
      - reduction_2
      - reduction_4
      image_height: 224
      image_width: 480
    cross_view:
      heads: 4
      dim_head: 32
      qkv_bias: true
      skip: true
      no_image_features: false
      image_height: 224
      image_width: 480
    bev_embedding:
      sigma: 1.0
      bev_height: 200
      bev_width: 200
      h_meters: 100.0
      w_meters: 100.0
      offset: 0.0
      decoder_blocks:
      - 128
      - 128
      - 64
  decoder:
    _target_: cross_view_transformer.model.decoder.Decoder
    dim: 128
    blocks:
    - 128
    - 128
    - 64
    residual: true
    factor: 2
data:
  dataset: nuscenes_generated
  num_classes: 12
  version: v1.0-trainval
  dataset_dir: /data2/zjl/nuScenes
  labels_dir: /data2/zjl/nuScenes/cvt_labels_nuscenes_v2
  cameras:
  - - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  label_indices:
  - - 4
    - 5
    - 6
    - 7
    - 8
    - 10
    - 11
  bev:
    h: 200
    w: 200
    h_meters: 100.0
    w_meters: 100.0
    offset: 0.0
  augment: none
  image:
    h: 224
    w: 480
    top_crop: 46
visualization:
  _target_: cross_view_transformer.visualizations.nuscenes_viz.NuScenesViz
  label_indices:
  - - 4
    - 5
    - 6
    - 7
    - 8
    - 10
    - 11
loss:
  visible_weight: 1.0
  visible:
    _target_: cross_view_transformer.losses.BinarySegmentationLoss
    label_indices:
    - - 4
      - 5
      - 6
      - 7
      - 8
      - 10
      - 11
    gamma: 2.0
    alpha: -1.0
    min_visibility: 2
  center_weight: 0.1
  center:
    _target_: cross_view_transformer.losses.CenterLoss
    gamma: 2.0
    min_visibility: 2
metrics:
  iou:
    _target_: cross_view_transformer.metrics.IoUMetric
    label_indices:
    - - 4
      - 5
      - 6
      - 7
      - 8
      - 10
      - 11
    min_visibility: 2
  iou_with_occlusions:
    _target_: cross_view_transformer.metrics.IoUMetric
    label_indices:
    - - 4
      - 5
      - 6
      - 7
      - 8
      - 10
      - 11
